# Generated by Django 5.0.6 on 2024-07-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment_stripe_payment_url_payment_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на оплату в Stripe'),
        ),
    ]
