# Generated by Django 5.0.6 on 2024-06-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название курса', max_length=100, verbose_name='Название курса')),
                ('course_preview', models.ImageField(blank=True, help_text='Загрузите фото курса', null=True, upload_to='materials/photo', verbose_name='Фото')),
                ('description', models.TextField(blank=True, help_text='Укажите описание курса', null=True, verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название урока', max_length=100, verbose_name='Урок')),
                ('lesson_preview', models.ImageField(blank=True, help_text='Загрузите фото урока', null=True, upload_to='materials/photo', verbose_name='Фото')),
                ('link_to_video', models.URLField(blank=True, help_text='Укажите ссылку на видео урока', null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, help_text='Выберите курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
